### ISSUE TITLE
Hide passwords while typing

### ISSUE THREAD

**Issue by ChrisLovering** [AnonymousX86/Python-Password#2]
The library `getpass` that ships with python that can be used when asking a user to enter a password. This hides the characters that they type while entering the password.

To use it, first import the module and then replace and `input()` calls with `getpass()` instead. Like so:
```python3
from getpass import getpass
pswd = getpass('Password:')
```

**Comment by AnonymousX86** [comment]
For now only a few inputs are visible, it will be changed in next update.
