### ISSUE TITLE
Use context managers instead of manaing resources

### ISSUE THREAD

**Issue by ChrisLovering** [AnonymousX86/Python-Password#3]
Whenever you find yourself manually handling resources you should first think 'Is there a context manager for this?'.

Context managers handle the gathering and releasing of resources for you. 
This link explain them fairly well: https://jeffknupp.com/blog/2016/03/07/python-with-context-managers/

There are a few places you have used a context manager within the script, which is great! However, there are some places you haven't used them and haven't closed the file!

You can also use a context manager for `sqlite3` cursors too. These give the added benefit of automatically committing or rolling back transactions.
You can read about them here: https://docs.python.org/2/library/sqlite3.html#using-the-connection-as-a-context-manager

**Comment by AnonymousX86** [comment]
Thanks, I'll change this.
