### ISSUE TITLE
[BUG] Hard to remove passwords with special characters in aliases

### ISSUE THREAD

**Issue by sachapomme** [AnonymousX86/Python-Password#5]
**Description of the bug**
It is possible that the alias of the password has some weird characters that makes the password hard to remove from the database.

**To Reproduce**
1. Create a new entry with an alias like a tab at the end.
2. The tab is displayed as a crossed box. And you may not remember which character it is later on.

**Expected behavior**
I think you should make an extra safety step and check that passwords are only a-z, A-Z and 0-9 characters or something like that, to make the passwords easy to remove.

**Screenshots**
![bug](https://user-images.githubusercontent.com/62360239/82250952-ae5b3a80-994c-11ea-9374-ddbadff1e162.png)

**Version**
v0.2.2

**Comment by AnonymousX86** [comment]
Thanks so much for request. 👋
I'll add checking like that shortly.

**Comment by sachapomme** [comment]
Okay, glad to hear that I could help!
Amazing looking program!
